spack:
  concretizer:
    unify: true
  view: false

  config:
    deprecated: true

  compilers:
   - compiler:
      spec: gcc@10.3.0
      paths:
         cc: /usr/bin/gcc-10
         cxx: /usr/bin/g++-10
         f77: /usr/bin/gfortran-10
         fc: /usr/bin/gfortran-10
      flags: {}
      operating_system: ubuntu20.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  # Basic package config from configs/common/packages.yaml
  # Additional package config for container
  packages:
    autoconf:
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
     externals:
      - spec: automake@1.16.1
        prefix: /usr
    bash:
      externals:
      - spec: bash@5.0.17
        prefix: /usr
    binutils:
      externals:
      - spec: binutils@2.34
        prefix: /usr
    bzip2:
      externals:
      - spec: bzip2@1.0.8
        prefix: /usr
    curl:
      externals:
      - spec: curl@7.68.0+gssapi+ldap+nghttp2
        prefix: /usr
    diffutils:
      externals:
      - spec: diffutils@3.7
        prefix: /usr
    findutils:
      externals:
      - spec: findutils@4.7.0
        prefix: /usr
    git:
      externals:
      - spec: git@2.25.1~tcltk
        prefix: /usr
      buildable: false
    git-lfs:
      externals:
      - spec: git-lfs@2.9.2
        prefix: /usr
      - spec: git-lfs@2
        prefix: /usr
      buildable: false
    gmake:
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
    ncurses:
      externals:
      - spec: ncurses@6.2
        prefix: /usr
    openssh:
      externals:
      - spec: openssh@8.2p1
        prefix: /usr
    pkg-config:
      externals:
      - spec: pkg-config@0.29.1
        prefix: /usr
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    openssl:
      buildable: false
      externals:
      - spec: openssl@1.1.1z
        prefix: /usr
    perl:
      externals:
      - spec: perl@5.30.0~cpanm+shared+threads
        prefix: /usr
    python:
      externals:
      - spec: python@3.8.10+bz2+ctypes+dbm+ensurepip+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
        prefix: /usr
    sed:
      externals:
      - spec: sed@4.7
        prefix: /usr
    tar:
      externals:
      - spec: tar@1.30
        prefix: /usr
    xz:
      externals:
      - spec: xz@5.2.4
        prefix: /usr

  specs: []

  container:

    # Select the format of the recipe e.g. docker,
    # singularity or anything else that is currently supported
    format: docker
    # How to use:
    #$ spack containerize > Dockerfile
    #$ docker build -t myimage .
    #$ docker run -it myimage

    #format: singularity
    # How to use:
    #$ spack containerize > hdf5.def
    #$ sudo singularity build hdf5.sif hdf5.def

    # Sets the base images for the stages where Spack builds the
    # software or where the software gets installed after being built..
    images:
      os: ubuntu:20.04
      spack:
        url: https://github.com/noaa-emc/spack
        ref: jcsda_emc_spack_stack
        resolve_sha: false
      
    # Whether or not to strip binaries
    strip: true

    ## Additional system packages that are needed at runtime
    os_packages:
      build:
      - libcurl4-openssl-dev
      - libncurses-dev
      - libssl-dev
      - autotools-dev
      - autoconf
      - pkg-config
      - gcc-10
      - g++-10
      - gfortran-10
      - cpp-10
      - git
      - git-lfs
      - libpython3-dev
      final:
      - gcc-10
      - g++-10
      - gfortran-10
      - cpp-10
      - git
      - git-lfs

    ## Extra instructions
    #extra_instructions:
    #  build:
    #    # Needed for gfortran-11
    #    RUN add-apt-repository ppa:ubuntu-toolchain-r/test
    #    RUN apt-get install gfortran-11
    #  final: |
    #    RUN echo 'export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][gromacs]\[$(tput setaf 2)\]\u\[$(tput sgr0)\]:\w $ "' >> ~/.bashrc

    # Labels for the image
    labels:
      app: ""
      mpi: "openmpi"
