name: macos-llvm-clang-build
on: workflow_dispatch

# Use custom shell with -l so .bash_profile is sourced
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install-env
        uses: ./.github/actions/setup-spack-stack
        with:
          template: jedi-ufs-all-macos-clang
          compiler: clang
          mpi: openmpi
          path: ${{ github.workspace }}
